# Generated by Django 4.2.7 on 2026-01-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('api', 'API Documentation'), ('guide', 'User Guide'), ('reference', 'Reference'), ('tutorial', 'Tutorial'), ('changelog', 'Changelog')], default='api', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template_id'], name='templates_templat_fb899b_idx'), models.Index(fields=['category'], name='templates_categor_206a35_idx'), models.Index(fields=['created_by', '-created_at'], name='templates_created_9f19e3_idx')],
            },
        ),
    ]
