# Generated by Django 4.2.7 on 2026-01-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roadmap Item',
                'verbose_name_plural': 'Roadmap Items',
                'db_table': 'roadmap_items',
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['item_id'], name='roadmap_ite_item_id_e47e6b_idx'), models.Index(fields=['status'], name='roadmap_ite_status_3e0a88_idx'), models.Index(fields=['due_date'], name='roadmap_ite_due_dat_dd36d7_idx'), models.Index(fields=['created_by', '-created_at'], name='roadmap_ite_created_08f63e_idx')],
            },
        ),
    ]
