# Generated by Django 4.2.7 on 2026-01-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityScan',
            fields=[
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('issues', models.JSONField(blank=True, default=list)),
                ('score', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('critical_issues', models.IntegerField(default=0)),
                ('warning_issues', models.IntegerField(default=0)),
                ('info_issues', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessibility_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessibility Scan',
                'verbose_name_plural': 'Accessibility Scans',
                'db_table': 'accessibility_scans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scan_id'], name='accessibili_scan_id_bb636a_idx'), models.Index(fields=['url'], name='accessibili_url_48f530_idx'), models.Index(fields=['scanned_by', '-created_at'], name='accessibili_scanned_d54ba0_idx'), models.Index(fields=['-created_at'], name='accessibili_created_2e3d03_idx')],
            },
        ),
    ]
