# Generated by Django 4.2.7 on 2026-01-23 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILearningSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=255)),
                ('patterns_learned', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Learning Session',
                'verbose_name_plural': 'AI Learning Sessions',
                'db_table': 'ai_learning_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.ailearningsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message_id'], name='chat_messag_message_5a6679_idx'), models.Index(fields=['session', 'created_at'], name='chat_messag_session_597c4e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ailearningsession',
            index=models.Index(fields=['session_id'], name='ai_learning_session_fea39b_idx'),
        ),
        migrations.AddIndex(
            model_name='ailearningsession',
            index=models.Index(fields=['status'], name='ai_learning_status_a9156d_idx'),
        ),
        migrations.AddIndex(
            model_name='ailearningsession',
            index=models.Index(fields=['-created_at'], name='ai_learning_created_b43dd0_idx'),
        ),
    ]
