# Generated by Django 4.2.7 on 2026-03-14 00:39
# Depends on all apps that had FK to core.User so they migrate to auth.User first.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers_alter_user_theme_preference_and_more'),
        ('durgasman', '0002_alter_user_fk_to_auth_user'),
        ('durgasflow', '0002_replace_user_fk_with_uuid'),  # durgasflow already uses CharField for user
        ('ai_agent', '0002_alter_user_fk_to_auth_user'),
        ('knowledge', '0002_alter_user_fk_to_auth_user'),
        ('roadmap', '0002_alter_user_fk_to_auth_user'),
        ('page_builder', '0002_alter_user_fk_to_auth_user'),
        ('json_store', '0002_alter_user_fk_to_auth_user'),
        ('templates', '0002_alter_user_fk_to_auth_user'),
        ('operations', '0002_alter_user_fk_to_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
