# Generated by Django 4.2.7 on 2026-01-23 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('knowledge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('pattern', 'Pattern'), ('documentation', 'Documentation'), ('code_snippet', 'Code Snippet'), ('best_practice', 'Best Practice'), ('api_pattern', 'API Pattern'), ('architecture', 'Architecture')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Base Item',
                'verbose_name_plural': 'Knowledge Base Items',
                'db_table': 'knowledge_base',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['knowledge_id'], name='knowledge_b_knowled_3d481b_idx'), models.Index(fields=['pattern_type'], name='knowledge_b_pattern_dd278a_idx'), models.Index(fields=['-updated_at'], name='knowledge_b_updated_9fb371_idx')],
            },
        ),
    ]
