# Generated by Django 4.2.16 on 2026-04-09 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="N8nCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("api_key", "API Key"),
                            ("bearer_token", "Bearer Token"),
                            ("basic_auth", "Basic Auth"),
                            ("oauth2", "OAuth 2.0"),
                            ("custom", "Custom"),
                        ],
                        default="api_key",
                        max_length=20,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "N8n Credential",
                "verbose_name_plural": "N8n Credentials",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="N8nExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("webhook", "Webhook"),
                            ("schedule", "Schedule"),
                            ("event", "Event"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("trigger_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("node_results", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_stack", models.TextField(blank=True, default="")),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "triggered_by",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "N8n Execution",
                "verbose_name_plural": "N8n Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="N8nWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "n8n_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="id / workflow_id from n8n JSON",
                        max_length=200,
                    ),
                ),
                (
                    "n8n_version_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("webhook", "Webhook"),
                            ("schedule", "Schedule"),
                            ("event", "Event"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("graph_data", models.JSONField(blank=True, default=dict)),
                (
                    "s3_bucket_id",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "s3_file_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. json/<uuid>.json",
                        max_length=500,
                    ),
                ),
                ("node_count", models.PositiveIntegerField(default=0)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "N8n Workflow",
                "verbose_name_plural": "N8n Workflows",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="N8nExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_id", models.CharField(blank=True, default="", max_length=200)),
                ("node_name", models.CharField(blank=True, default="", max_length=300)),
                ("node_type", models.CharField(blank=True, default="", max_length=200)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="durgasflow.n8nexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Log",
                "verbose_name_plural": "Execution Logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="n8nexecution",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="durgasflow.n8nworkflow",
            ),
        ),
    ]
