# Generated by Django 4.2.7 on 2026-01-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durgasflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='triggered_by',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
