"""Hardcoded Contact360 product roadmap for DocsAI (no markdown loader)."""

CONTACT360_VERSION = "1.1.0 (in_progress)"
CONTACT360_PRODUCT = "Contact360"
CONTACT360_CURRENT_FOCUS = (
    "Billing and payments (Stage 1.3) and bulk validation hardening (Stage 2.4)."
)

CONTACT360_ROADMAP_STAGES = [
    {
        "id": "1.1",
        "stage": "Stage 1.1",
        "title": "User & Authentication System",
        "status": "completed",
        "depends_on": "Foundation platform setup",
        "risk": "Session handling regressions across dashboard and extension",
        "definition_of_done": "User can register, sign in, and begin usage with starter credits",
        "kpi": "Signup-to-first-action conversion; auth failure rate",
        "ships_in": "1.0.0",
        "features": [
            "Email Signup & Login",
            "Basic User Profile",
            "Auto credit assignment (50 credits)",
            "Session management",
        ],
    },
    {
        "id": "1.2",
        "stage": "Stage 1.2",
        "title": "Credit Management System (CORE)",
        "status": "completed",
        "depends_on": "Stage 1.1",
        "risk": "Incorrect deduction and lapse behavior can block valid usage",
        "definition_of_done": "Finder deductions and entitlement checks are consistent",
        "kpi": "Credit ledger consistency",
        "ships_in": "1.0.0",
        "features": [
            "Credit balance tracking",
            "Credit deduction per action: Finder only (Verifier costs 0 credits)",
            "Free credits (50 on signup)",
            "Credit usage logs (basic)",
            "Block actions when credits = 0",
            "Credits will lapse when the premium pack is over.",
        ],
    },
    {
        "id": "1.4",
        "stage": "Stage 1.4",
        "title": "Email Finder Engine",
        "status": "completed",
        "depends_on": "Stages 1.1 and 1.2",
        "risk": "Provider inconsistency can reduce candidate quality",
        "definition_of_done": "Finder returns normalized candidates and logs",
        "kpi": "Finder success rate; median latency",
        "ships_in": "1.0.0",
        "features": [
            "Predefined pattern generation (10 formats)",
            "Generate possible valid email",
            "Historical logs should show on the same page",
        ],
    },
    {
        "id": "1.5",
        "stage": "Stage 1.5",
        "title": "Email Verification Engine",
        "status": "completed",
        "depends_on": "Stage 1.4",
        "risk": "External signal variability",
        "definition_of_done": "Verification statuses are normalized in single and bulk flows",
        "kpi": "Verification completion rate",
        "ships_in": "1.0.0",
        "features": [
            "Integrate 1 external API (e.g., Mailvetter)",
            "Basic checks: Valid / Delivered-Catchall / Un delivered-Catchall / Invalid / Not Found — confidence score (if API provides)",
        ],
    },
    {
        "id": "1.6",
        "stage": "Stage 1.6",
        "title": "Results Engine",
        "status": "completed",
        "depends_on": "Stages 1.4 and 1.5",
        "risk": "UI inconsistency in status/confidence rendering",
        "definition_of_done": "Best result plus auditable logs shown in UI",
        "kpi": "Result view completion rate",
        "ships_in": "1.0.0",
        "features": [
            "Show: Best email; Status (Valid / Delivered-Catchall / Un delivered-Catchall / Invalid / Not Found); Confidence (if API provides)",
            "Show the logs of email validation",
        ],
    },
    {
        "id": "1.8",
        "stage": "Stage 1.8",
        "title": "Bulk Processing — Validation (LIMITED MVP)",
        "status": "in_progress",
        "depends_on": "Stages 1.4, 1.5, and 1.6",
        "risk": "Processor partial failures and resume edge cases",
        "definition_of_done": "Upload, process, resume, and download are reliable",
        "kpi": "Bulk success rate; resume success rate",
        "ships_in": "1.1.0",
        "features": [
            "CSV upload (basic)",
            "Current processor concurrency: finder stream = 3, verifier stream = 5",
        ],
    },
    {
        "id": "1.10",
        "stage": "Stage 1.10",
        "title": "Billing & Payments",
        "status": "in_progress",
        "depends_on": "Stages 1.1 and 1.2",
        "risk": "Payment confirmation and delayed crediting mismatch",
        "definition_of_done": "Users can purchase packs and receive credits through approved flow",
        "kpi": "Payment-to-crediting turnaround time",
        "ships_in": "1.1.0",
        "features": [
            "Credit purchase system",
            "2–3 pricing plans only",
            "Manual Payment Integration (whatever is suitable)",
            "No subscription complexity (credit packs only)",
        ],
    },
    {
        "id": "1.11",
        "stage": "Stage 1.11",
        "title": "Analytics for the User (Minimal)",
        "status": "planned",
        "depends_on": "Stages 1.2 and 1.10",
        "risk": "Usage metrics mismatch with billing records",
        "definition_of_done": "Users can view basic usage and entitlement summary",
        "kpi": "Usage summary adoption",
        "ships_in": "1.2.0",
        "features": [
            "User Logs",
            "Credits used",
            "Package / Expiry showing",
        ],
    },
    {
        "id": "1.12",
        "stage": "Stage 1.12",
        "title": "Notifications (Minimal)",
        "status": "planned",
        "depends_on": "Stages 1.10 and 1.11",
        "risk": "Late/incorrect notifications",
        "definition_of_done": "Low-credit and payment-success cues are reliable",
        "kpi": "Notification correctness",
        "ships_in": "1.2.0",
        "features": [
            "Low credit warning (UI only)",
            "Payment success message",
            "No email automation in v1",
        ],
    },
    {
        "id": "1.13",
        "stage": "Stage 1.13",
        "title": "Analytics Admin Panel (Basic Control)",
        "status": "planned",
        "depends_on": "Stages 1.2 and 1.11",
        "risk": "Admin adjustments without clear audit context",
        "definition_of_done": "Admin can audit and adjust core entitlement state",
        "kpi": "Admin correction turnaround time",
        "ships_in": "1.2.0",
        "features": [
            "View users (Package & Expiry)",
            "View credits",
            "Manually adjust credits",
            "View usage logs",
        ],
    },
    {
        "id": "1.14",
        "stage": "Stage 1.14",
        "title": "Security (Basic Layer)",
        "status": "planned",
        "depends_on": "Stage 1.1 and middleware rollout",
        "risk": "High-volume abuse and spam traffic",
        "definition_of_done": "Baseline throttling and abuse controls active on core APIs",
        "kpi": "Rate-limited abuse attempts",
        "ships_in": "1.2.0",
        "features": [
            "Rate limiting (basic)",
            "Prevent spam usage",
        ],
    },
    {
        "id": "2.1",
        "stage": "Stage 2.1",
        "title": "Advanced search filters",
        "status": "planned",
        "depends_on": "Connectra index quality and VQL parser support",
        "risk": "Filter complexity can increase query latency",
        "definition_of_done": "Advanced contacts/companies filters are production-ready",
        "kpi": "Filter query success and P95 latency",
        "ships_in": "2.0.0",
        "features": [
            "Advanced contact and company filters",
            "VQL-driven query expansion",
        ],
    },
    {
        "id": "2.2",
        "stage": "Stage 2.2",
        "title": "Enrichment and deduplication",
        "status": "planned",
        "depends_on": "Stage 2.1",
        "risk": "Duplicate profile and confidence mismatch",
        "definition_of_done": "Enrichment quality improves with deterministic dedupe logic",
        "kpi": "Duplicate reduction and enrichment completeness",
        "ships_in": "2.0.0",
        "features": [
            "Record enrichment pipeline",
            "Deduplication controls",
        ],
    },
    {
        "id": "2.3",
        "stage": "Stage 2.3",
        "title": "Search quality and performance",
        "status": "planned",
        "depends_on": "Stages 2.1 and 2.2",
        "risk": "Index refresh and relevance tuning instability",
        "definition_of_done": "Search relevance and latency goals are achieved",
        "kpi": "Search relevance score and P95 response time",
        "ships_in": "2.0.0",
        "features": [
            "Relevance tuning",
            "Performance optimization",
        ],
    },
    {
        "id": "2.4",
        "stage": "Stage 2.4",
        "title": "Dashboard search UX expansion",
        "status": "planned",
        "depends_on": "Stages 2.1 and 2.3",
        "risk": "Increased UI complexity",
        "definition_of_done": "Advanced filter UX is available in dashboard",
        "kpi": "Search-to-export conversion",
        "ships_in": "2.0.0",
        "features": [
            "Advanced dashboard filters",
            "Improved search interaction patterns",
        ],
    },
    {
        "id": "2.5",
        "stage": "Stage 2.5",
        "title": "Email app credential security hardening",
        "status": "in_progress",
        "depends_on": "Stage 2.4 and mailbox API session contract",
        "risk": "Plaintext IMAP credential exposure in frontend runtime",
        "definition_of_done": "Email app uses tokenized mailbox sessions and removes plaintext credential transport/storage",
        "kpi": "Credential exposure incidents",
        "ships_in": "2.0.0",
        "features": [
            "Replace X-Email/X-Password transport with token exchange",
            "Remove localStorage mailbox credential persistence",
            "Server-managed mailbox secret boundary",
        ],
    },
    {
        "id": "3.1",
        "stage": "Stage 3.1",
        "title": "Extension auth and session hardening",
        "status": "planned",
        "depends_on": "Appointment360 auth contracts",
        "risk": "Session/token refresh failures in browser context",
        "definition_of_done": "Stable extension auth session lifecycle",
        "kpi": "Extension auth failure rate",
        "ships_in": "3.0.0",
        "features": [
            "Token refresh hardening",
            "Session stability improvements",
        ],
    },
    {
        "id": "3.2",
        "stage": "Stage 3.2",
        "title": "Sales Navigator ingestion optimization",
        "status": "planned",
        "depends_on": "Stage 3.1",
        "risk": "Source-side data variability",
        "definition_of_done": "Ingestion throughput and accuracy targets are met",
        "kpi": "Ingestion error rate",
        "ships_in": "3.0.0",
        "features": [
            "Ingestion pipeline optimization",
            "Improved mapping quality",
        ],
    },
    {
        "id": "3.3",
        "stage": "Stage 3.3",
        "title": "Sync integrity and conflict handling",
        "status": "planned",
        "depends_on": "Stages 3.1 and 3.2",
        "risk": "Duplicate writes and state divergence",
        "definition_of_done": "Deterministic conflict resolution is implemented",
        "kpi": "Conflict auto-resolution success rate",
        "ships_in": "3.0.0",
        "features": [
            "Conflict detection rules",
            "Deterministic merge behavior",
        ],
    },
    {
        "id": "3.4",
        "stage": "Stage 3.4",
        "title": "Extension telemetry and reliability",
        "status": "planned",
        "depends_on": "Stage 3.3",
        "risk": "Insufficient production observability",
        "definition_of_done": "Telemetry and error diagnostics are production-ready",
        "kpi": "Error triage time",
        "ships_in": "3.0.0",
        "features": [
            "Extension telemetry events",
            "Operational error monitoring",
        ],
    },
    {
        "id": "4.1",
        "stage": "Stage 4.1",
        "title": "Contact AI dashboard integration",
        "status": "planned",
        "depends_on": "contact.ai API contracts",
        "risk": "Low-quality AI output adoption",
        "definition_of_done": "AI output appears in core dashboard workflows",
        "kpi": "AI-assisted action adoption",
        "ships_in": "4.0.0",
        "features": [
            "AI-assisted workflow entry points",
            "Dashboard integration layer",
        ],
    },
    {
        "id": "4.2",
        "stage": "Stage 4.2",
        "title": "AI confidence and explainability",
        "status": "planned",
        "depends_on": "Stage 4.1",
        "risk": "User trust degradation",
        "definition_of_done": "Confidence/explanation metadata is visible and usable",
        "kpi": "AI output acceptance rate",
        "ships_in": "4.0.0",
        "features": [
            "Confidence indicators",
            "Explainability metadata",
        ],
    },
    {
        "id": "4.3",
        "stage": "Stage 4.3",
        "title": "AI usage limits and cost controls",
        "status": "planned",
        "depends_on": "Stages 1.2 and 4.1",
        "risk": "Unbounded model spend",
        "definition_of_done": "Quotas and spend guardrails are enforced",
        "kpi": "AI cost per active user",
        "ships_in": "4.0.0",
        "features": [
            "Usage quota controls",
            "Cost guardrail enforcement",
        ],
    },
    {
        "id": "4.4",
        "stage": "Stage 4.4",
        "title": "Prompt/version governance",
        "status": "planned",
        "depends_on": "Stages 4.1 and 4.2",
        "risk": "Prompt drift and regression risk",
        "definition_of_done": "Prompt versioning and rollback governance are operational",
        "kpi": "Prompt rollback time",
        "ships_in": "4.0.0",
        "features": [
            "Prompt version tracking",
            "Rollback governance workflow",
        ],
    },
    {
        "id": "4.5",
        "stage": "Stage 4.5",
        "title": "Extension shell delivery",
        "status": "planned",
        "depends_on": "Stage 3.4 and Sales Navigator backend completion",
        "risk": "Backend-ready extension flow remains non-operational without browser shell",
        "definition_of_done": "Manifest, background worker, content script, and popup UI are production-ready",
        "kpi": "Sales Navigator capture success rate",
        "ships_in": "4.5.0",
        "features": [
            "manifest.json with CSP and permissions",
            "background/service worker wiring",
            "content script extraction flow",
            "popup progress and error handling UI",
        ],
    },
    {
        "id": "5.1",
        "stage": "Stage 5.1",
        "title": "Reliability baseline and SLO definition",
        "status": "planned",
        "depends_on": "Stable 4.x APIs",
        "risk": "Undefined service reliability targets",
        "definition_of_done": "SLOs and error budgets are active",
        "kpi": "SLO attainment rate",
        "ships_in": "5.1.0",
        "features": ["Service SLOs", "Reliability dashboards"],
    },
    {
        "id": "5.0",
        "stage": "Stage 5.0",
        "title": "Dashboard AI chat runtime wiring",
        "status": "in_progress",
        "depends_on": "Stage 4.2 and Appointment360 aiChat contract",
        "risk": "AI chat UX remains mock-backed and cannot produce real responses",
        "definition_of_done": "Dashboard AI chat calls live Appointment360 aiChat mutation with auth and error handling",
        "kpi": "AI chat successful response rate",
        "ships_in": "5.0.0",
        "features": [
            "Replace mockSend path with GraphQL aiChat integration",
            "Wire loading/error states to runtime responses",
            "Persist basic chat session metadata",
        ],
    },
    {
        "id": "5.2",
        "stage": "Stage 5.2",
        "title": "Idempotency and consistency hardening",
        "status": "planned",
        "depends_on": "Stage 5.1",
        "risk": "Duplicate writes in critical flows",
        "definition_of_done": "Critical writes enforce idempotency",
        "kpi": "Duplicate side-effect incidents",
        "ships_in": "5.2.0",
        "features": ["Idempotency keys", "Consistency checks"],
    },
    {
        "id": "5.3",
        "stage": "Stage 5.3",
        "title": "Queue and worker resilience",
        "status": "planned",
        "depends_on": "Stage 5.2",
        "risk": "Queue lag and poisoned jobs",
        "definition_of_done": "DLQ and replay controls are active",
        "kpi": "Queue lag P95",
        "ships_in": "5.3.0",
        "features": ["DLQ and replay", "Retry strategy"],
    },
    {
        "id": "5.4",
        "stage": "Stage 5.4",
        "title": "Observability and diagnostics maturity",
        "status": "planned",
        "depends_on": "Stage 5.3",
        "risk": "Slow incident triage",
        "definition_of_done": "Correlated logs/traces/alerts are available",
        "kpi": "MTTR",
        "ships_in": "5.4.0",
        "features": ["Trace correlation", "Operational alerts"],
    },
    {
        "id": "5.5",
        "stage": "Stage 5.5",
        "title": "Performance optimization wave",
        "status": "planned",
        "depends_on": "Stage 5.4",
        "risk": "Latency bottlenecks under load",
        "definition_of_done": "Critical latency hotspots are optimized",
        "kpi": "API P95 latency",
        "ships_in": "5.5.0",
        "features": ["Hot-path tuning", "Throughput improvements"],
    },
    {
        "id": "5.6",
        "stage": "Stage 5.6",
        "title": "Storage and artifact lifecycle hardening",
        "status": "planned",
        "depends_on": "Stage 5.5",
        "risk": "Artifact corruption and orphan files",
        "definition_of_done": "Artifact lifecycle controls are enforced",
        "kpi": "Artifact integrity success rate",
        "ships_in": "5.6.0",
        "features": ["Integrity checks", "Retention cleanup"],
    },
    {
        "id": "5.7",
        "stage": "Stage 5.7",
        "title": "Cost reliability and budget guardrails",
        "status": "planned",
        "depends_on": "Stage 5.6",
        "risk": "Unbounded operating costs",
        "definition_of_done": "Budget guardrails are active",
        "kpi": "Cost per active user",
        "ships_in": "5.7.0",
        "features": ["Cost guardrails", "Spend alerts"],
    },
    {
        "id": "5.8",
        "stage": "Stage 5.8",
        "title": "Security and abuse resilience at scale",
        "status": "planned",
        "depends_on": "Stage 5.7",
        "risk": "Abuse at higher traffic",
        "definition_of_done": "Abuse controls and limits are active",
        "kpi": "Blocked abuse attempts",
        "ships_in": "5.8.0",
        "features": ["Advanced rate limits", "Abuse detection"],
    },
    {
        "id": "5.9",
        "stage": "Stage 5.9",
        "title": "RC hardening before 6.0.0",
        "status": "planned",
        "depends_on": "Stages 5.1-5.8",
        "risk": "Late reliability regressions",
        "definition_of_done": "Release-candidate reliability checks pass",
        "kpi": "RC defect escape rate",
        "ships_in": "5.9.0",
        "features": ["RC test suite", "Runbook validation"],
    },
    {
        "id": "6.1",
        "stage": "Stage 6.1",
        "title": "RBAC model foundation",
        "status": "planned",
        "depends_on": "Stage 5.9",
        "risk": "Inconsistent authorization",
        "definition_of_done": "Role hierarchy and permissions are enforced",
        "kpi": "Unauthorized access incidents",
        "ships_in": "6.1.0",
        "features": ["Role matrix", "Permission checks"],
    },
    {
        "id": "6.2",
        "stage": "Stage 6.2",
        "title": "Service-level authorization enforcement",
        "status": "planned",
        "depends_on": "Stage 6.1",
        "risk": "Bypass in internal routes",
        "definition_of_done": "Service authz controls are standardized",
        "kpi": "Protected route coverage",
        "ships_in": "6.2.0",
        "features": ["Internal authz middleware", "Policy validation"],
    },
    {
        "id": "6.3",
        "stage": "Stage 6.3",
        "title": "Admin governance controls",
        "status": "planned",
        "depends_on": "Stage 6.2",
        "risk": "Unsafe admin actions",
        "definition_of_done": "Admin approvals and audit details are mandatory",
        "kpi": "Audited admin action coverage",
        "ships_in": "6.3.0",
        "features": ["Approval flow", "Reason-coded changes"],
    },
    {
        "id": "6.4",
        "stage": "Stage 6.4",
        "title": "Audit and compliance event model",
        "status": "planned",
        "depends_on": "Stage 6.3",
        "risk": "Missing compliance evidence",
        "definition_of_done": "Immutable audit event schema is active",
        "kpi": "Audit completeness",
        "ships_in": "6.4.0",
        "features": ["Audit event schema", "Compliance reports"],
    },
    {
        "id": "6.5",
        "stage": "Stage 6.5",
        "title": "Data governance and lifecycle controls",
        "status": "planned",
        "depends_on": "Stage 6.4",
        "risk": "Retention policy drift",
        "definition_of_done": "Data lifecycle policy enforcement is active",
        "kpi": "Lifecycle policy conformance",
        "ships_in": "6.5.0",
        "features": ["Data classification", "Retention/deletion policy"],
    },
    {
        "id": "6.6",
        "stage": "Stage 6.6",
        "title": "Tenant and policy isolation",
        "status": "planned",
        "depends_on": "Stage 6.5",
        "risk": "Cross-tenant leakage",
        "definition_of_done": "Tenant isolation is validated",
        "kpi": "Isolation test pass rate",
        "ships_in": "6.6.0",
        "features": ["Tenant context enforcement", "Isolation tests"],
    },
    {
        "id": "6.7",
        "stage": "Stage 6.7",
        "title": "Security posture uplift",
        "status": "planned",
        "depends_on": "Stage 6.6",
        "risk": "Weak privileged controls",
        "definition_of_done": "Secret and privileged controls are hardened",
        "kpi": "Security control coverage",
        "ships_in": "6.7.0",
        "features": ["Secret rotation", "Privileged access controls"],
    },
    {
        "id": "6.8",
        "stage": "Stage 6.8",
        "title": "Enterprise observability and reporting",
        "status": "planned",
        "depends_on": "Stage 6.7",
        "risk": "Insufficient enterprise visibility",
        "definition_of_done": "Enterprise reports and dashboards are available",
        "kpi": "Enterprise reporting completeness",
        "ships_in": "6.8.0",
        "features": ["Tenant-aware reports", "Governance dashboards"],
    },
    {
        "id": "6.9",
        "stage": "Stage 6.9",
        "title": "RC hardening before 7.0.0",
        "status": "planned",
        "depends_on": "Stages 6.1-6.8",
        "risk": "Authorization/compliance regressions",
        "definition_of_done": "Enterprise RC validation is complete",
        "kpi": "RC control failures",
        "ships_in": "6.9.0",
        "features": ["RC governance suite", "Access regression tests"],
    },
    {
        "id": "7.1",
        "stage": "Stage 7.1",
        "title": "Unified analytics taxonomy foundation",
        "status": "planned",
        "depends_on": "Stage 6.9",
        "risk": "Inconsistent metric semantics",
        "definition_of_done": "Canonical taxonomy is adopted",
        "kpi": "Schema conformance",
        "ships_in": "7.1.0",
        "features": ["Event dictionary", "Metric definitions"],
    },
    {
        "id": "7.2",
        "stage": "Stage 7.2",
        "title": "Instrumentation rollout",
        "status": "planned",
        "depends_on": "Stage 7.1",
        "risk": "Telemetry blind spots",
        "definition_of_done": "Core journeys are fully instrumented",
        "kpi": "Instrumentation coverage",
        "ships_in": "7.2.0",
        "features": ["Dashboard instrumentation", "Extension/backend instrumentation"],
    },
    {
        "id": "7.3",
        "stage": "Stage 7.3",
        "title": "Analytics ingestion and storage hardening",
        "status": "planned",
        "depends_on": "Stage 7.2",
        "risk": "Event loss/duplication",
        "definition_of_done": "Reliable analytics ingestion pipeline is active",
        "kpi": "Ingestion success rate",
        "ships_in": "7.3.0",
        "features": ["Dedupe and DLQ", "Schema evolution handling"],
    },
    {
        "id": "7.4",
        "stage": "Stage 7.4",
        "title": "Data quality and lineage controls",
        "status": "planned",
        "depends_on": "Stage 7.3",
        "risk": "Low trust in analytics data",
        "definition_of_done": "Quality and lineage checks are active",
        "kpi": "Data quality score",
        "ships_in": "7.4.0",
        "features": ["Freshness checks", "Lineage validation"],
    },
    {
        "id": "7.5",
        "stage": "Stage 7.5",
        "title": "User analytics experience v1",
        "status": "planned",
        "depends_on": "Stage 7.4",
        "risk": "Low feature adoption",
        "definition_of_done": "User analytics views are production-ready",
        "kpi": "Analytics feature usage",
        "ships_in": "7.5.0",
        "features": ["User KPI dashboards", "Trend views"],
    },
    {
        "id": "7.6",
        "stage": "Stage 7.6",
        "title": "Admin analytics and control center v1",
        "status": "planned",
        "depends_on": "Stage 7.5",
        "risk": "Insufficient admin insights",
        "definition_of_done": "DocsAI analytics controls are operational",
        "kpi": "Admin analytics engagement",
        "ships_in": "7.6.0",
        "features": ["Admin KPIs", "Control center views"],
    },
    {
        "id": "7.7",
        "stage": "Stage 7.7",
        "title": "Reporting and scheduled exports",
        "status": "planned",
        "depends_on": "Stage 7.6",
        "risk": "Report delivery failures",
        "definition_of_done": "Scheduled reporting and exports are reliable",
        "kpi": "Scheduled report success rate",
        "ships_in": "7.7.0",
        "features": ["Recurring reports", "Export delivery tracking"],
    },
    {
        "id": "7.8",
        "stage": "Stage 7.8",
        "title": "Analytics performance and cost optimization",
        "status": "planned",
        "depends_on": "Stage 7.7",
        "risk": "Expensive analytics operations",
        "definition_of_done": "Analytics query cost and latency are optimized",
        "kpi": "Cost per analytics workload",
        "ships_in": "7.8.0",
        "features": ["Query optimization", "Cost controls"],
    },
    {
        "id": "7.9",
        "stage": "Stage 7.9",
        "title": "RC hardening before 8.0.0",
        "status": "planned",
        "depends_on": "Stages 7.1-7.8",
        "risk": "Data platform regressions",
        "definition_of_done": "Analytics RC validation is complete",
        "kpi": "RC analytics defects",
        "ships_in": "7.9.0",
        "features": ["RC data validation", "Pipeline stress tests"],
    },
    {
        "id": "8.1",
        "stage": "Stage 8.1",
        "title": "Integration contract governance",
        "status": "planned",
        "depends_on": "Stage 7.9",
        "risk": "Partner contract drift",
        "definition_of_done": "Versioned integration contract governance is active",
        "kpi": "Contract compatibility rate",
        "ships_in": "8.1.0",
        "features": ["Contract policy", "Deprecation process"],
    },
    {
        "id": "8.2",
        "stage": "Stage 8.2",
        "title": "Partner identity and tenant-safe access",
        "status": "planned",
        "depends_on": "Stage 8.1",
        "risk": "Over-scoped external access",
        "definition_of_done": "Partner auth/scopes are enforced",
        "kpi": "Unauthorized partner access",
        "ships_in": "8.2.0",
        "features": ["Partner auth scopes", "Tenant-safe access controls"],
    },
    {
        "id": "8.3",
        "stage": "Stage 8.3",
        "title": "Public API minimum surface",
        "status": "planned",
        "depends_on": "Stage 8.2",
        "risk": "Unstable external API behavior",
        "definition_of_done": "Stable public API baseline is published",
        "kpi": "Public API success rate",
        "ships_in": "8.3.0",
        "features": ["Read/write partner APIs", "Contract tests"],
    },
    {
        "id": "8.4",
        "stage": "Stage 8.4",
        "title": "Webhook/event delivery platform v1",
        "status": "planned",
        "depends_on": "Stage 8.3",
        "risk": "Delivery reliability gaps",
        "definition_of_done": "Signed and retried webhook delivery is active",
        "kpi": "Webhook delivery success rate",
        "ships_in": "8.4.0",
        "features": ["Signed webhooks", "Retry and delivery logs"],
    },
    {
        "id": "8.5",
        "stage": "Stage 8.5",
        "title": "Replay and reconciliation for partners",
        "status": "planned",
        "depends_on": "Stage 8.4",
        "risk": "Unrecoverable missed events",
        "definition_of_done": "Replay and reconciliation tools are available",
        "kpi": "Replay recovery success rate",
        "ships_in": "8.5.0",
        "features": ["Replay endpoints", "Reconciliation checks"],
    },
    {
        "id": "8.6",
        "stage": "Stage 8.6",
        "title": "Connector framework baseline",
        "status": "planned",
        "depends_on": "Stage 8.5",
        "risk": "Connector implementation divergence",
        "definition_of_done": "Connector SDK/lifecycle baseline is defined",
        "kpi": "Connector onboarding lead time",
        "ships_in": "8.6.0",
        "features": ["Connector SDK", "Lifecycle management"],
    },
    {
        "id": "8.7",
        "stage": "Stage 8.7",
        "title": "Integration observability and support tooling",
        "status": "planned",
        "depends_on": "Stage 8.6",
        "risk": "Slow partner support triage",
        "definition_of_done": "Integration health and support controls are active",
        "kpi": "Partner issue MTTR",
        "ships_in": "8.7.0",
        "features": ["Integration health dashboards", "Support actions"],
    },
    {
        "id": "8.8",
        "stage": "Stage 8.8",
        "title": "Commercial entitlements and policy controls",
        "status": "planned",
        "depends_on": "Stage 8.7",
        "risk": "Uncontrolled ecosystem usage",
        "definition_of_done": "Integration entitlements are enforced by plan",
        "kpi": "Entitlement violation rate",
        "ships_in": "8.8.0",
        "features": ["Plan-based quotas", "Usage policy controls"],
    },
    {
        "id": "8.9",
        "stage": "Stage 8.9",
        "title": "RC hardening before 9.0.0",
        "status": "planned",
        "depends_on": "Stages 8.1-8.8",
        "risk": "Partner-facing regressions",
        "definition_of_done": "Integration RC validation is complete",
        "kpi": "RC partner regressions",
        "ships_in": "8.9.0",
        "features": ["Compatibility validation", "Partner RC tests"],
    },
    {
        "id": "9.1",
        "stage": "Stage 9.1",
        "title": "Tenant platform model standardization",
        "status": "planned",
        "depends_on": "Stage 8.9",
        "risk": "Tenant model drift",
        "definition_of_done": "Canonical tenant model is enforced",
        "kpi": "Tenant context coverage",
        "ships_in": "9.1.0",
        "features": ["Tenant model standard", "Context propagation"],
    },
    {
        "id": "9.2",
        "stage": "Stage 9.2",
        "title": "Self-serve workspace administration",
        "status": "planned",
        "depends_on": "Stage 9.1",
        "risk": "Support-heavy tenant operations",
        "definition_of_done": "Self-serve admin controls are operational",
        "kpi": "Self-serve admin success rate",
        "ships_in": "9.2.0",
        "features": ["Workspace admin controls", "Self-service settings"],
    },
    {
        "id": "9.3",
        "stage": "Stage 9.3",
        "title": "Plan entitlements and packaging engine",
        "status": "planned",
        "depends_on": "Stage 9.2",
        "risk": "Inconsistent feature gating",
        "definition_of_done": "Entitlement engine governs all channels",
        "kpi": "Entitlement enforcement accuracy",
        "ships_in": "9.3.0",
        "features": ["Entitlement engine", "Plan packaging rules"],
    },
    {
        "id": "9.4",
        "stage": "Stage 9.4",
        "title": "SLA/SLO operations foundation",
        "status": "planned",
        "depends_on": "Stage 9.3",
        "risk": "No enforceable service commitments",
        "definition_of_done": "SLA/SLO operational controls are active",
        "kpi": "SLA attainment rate",
        "ships_in": "9.4.0",
        "features": ["SLA reporting", "SLO alerting"],
    },
    {
        "id": "9.5",
        "stage": "Stage 9.5",
        "title": "Platform support and incident operations",
        "status": "planned",
        "depends_on": "Stage 9.4",
        "risk": "Slow support resolution",
        "definition_of_done": "Support diagnostics and playbooks are standardized",
        "kpi": "Support MTTR",
        "ships_in": "9.5.0",
        "features": ["Tenant diagnostics", "Incident playbooks"],
    },
    {
        "id": "9.6",
        "stage": "Stage 9.6",
        "title": "Data residency and policy overlays",
        "status": "planned",
        "depends_on": "Stage 9.5",
        "risk": "Region/policy non-compliance",
        "definition_of_done": "Residency and policy overlays are enforced",
        "kpi": "Policy compliance pass rate",
        "ships_in": "9.6.0",
        "features": ["Residency controls", "Tenant policy overlays"],
    },
    {
        "id": "9.7",
        "stage": "Stage 9.7",
        "title": "Cost governance and capacity forecasting",
        "status": "planned",
        "depends_on": "Stage 9.6",
        "risk": "Capacity and cost instability",
        "definition_of_done": "Cost and capacity governance controls are active",
        "kpi": "Forecast accuracy",
        "ships_in": "9.7.0",
        "features": ["Capacity forecasting", "Cost governance"],
    },
    {
        "id": "9.8",
        "stage": "Stage 9.8",
        "title": "Migration and lifecycle automation",
        "status": "planned",
        "depends_on": "Stage 9.7",
        "risk": "Manual migration risk",
        "definition_of_done": "Lifecycle automation for tenants is operational",
        "kpi": "Automated lifecycle success rate",
        "ships_in": "9.8.0",
        "features": ["Tenant migration automation", "Lifecycle orchestration"],
    },
    {
        "id": "9.9",
        "stage": "Stage 9.9",
        "title": "RC hardening before 10.0.0",
        "status": "planned",
        "depends_on": "Stages 9.1-9.8",
        "risk": "Late platform productization regressions",
        "definition_of_done": "Productization RC validation is complete",
        "kpi": "RC blocking issue count",
        "ships_in": "9.9.0",
        "features": ["RC platform validation", "Multi-tenant stress tests"],
    },
    {
        "id": "10.1",
        "stage": "Stage 10.1",
        "title": "Cross-surface contract unification",
        "status": "planned",
        "depends_on": "Stage 9.9",
        "risk": "Contract divergence",
        "definition_of_done": "Canonical contracts are unified across surfaces",
        "kpi": "Contract drift incidents",
        "ships_in": "10.1.0",
        "features": ["Contract unification", "Cross-surface compatibility checks"],
    },
    {
        "id": "10.2",
        "stage": "Stage 10.2",
        "title": "Unified identity, policy, and entitlement engine",
        "status": "planned",
        "depends_on": "Stage 10.1",
        "risk": "Conflicting policy decisions",
        "definition_of_done": "Single policy decision flow is active",
        "kpi": "Policy consistency rate",
        "ships_in": "10.2.0",
        "features": ["Unified policy engine", "Entitlement centralization"],
    },
    {
        "id": "10.3",
        "stage": "Stage 10.3",
        "title": "Workflow orchestration standardization",
        "status": "planned",
        "depends_on": "Stage 10.2",
        "risk": "Inconsistent workflow semantics",
        "definition_of_done": "Common workflow standards are enforced",
        "kpi": "Workflow failure variance",
        "ships_in": "10.3.0",
        "features": ["Workflow state standard", "Retry semantic alignment"],
    },
    {
        "id": "10.4",
        "stage": "Stage 10.4",
        "title": "Data model unification and lineage completeness",
        "status": "planned",
        "depends_on": "Stage 10.3",
        "risk": "Entity mismatch and lineage gaps",
        "definition_of_done": "Canonical data model and lineage are complete",
        "kpi": "Lineage completeness score",
        "ships_in": "10.4.0",
        "features": ["Canonical entity model", "Lineage controls"],
    },
    {
        "id": "10.5",
        "stage": "Stage 10.5",
        "title": "Platform UX consistency pass",
        "status": "planned",
        "depends_on": "Stage 10.4",
        "risk": "Cross-surface UX inconsistency",
        "definition_of_done": "Unified UX semantics are applied across surfaces",
        "kpi": "Cross-surface UX defect rate",
        "ships_in": "10.5.0",
        "features": ["UX semantic consistency", "Cross-surface behavior alignment"],
    },
    {
        "id": "10.6",
        "stage": "Stage 10.6",
        "title": "Operational excellence and automation",
        "status": "planned",
        "depends_on": "Stage 10.5",
        "risk": "Manual-heavy operations",
        "definition_of_done": "Release and recovery automation standards are active",
        "kpi": "Change failure rate",
        "ships_in": "10.6.0",
        "features": ["Automated release controls", "Automated recovery workflows"],
    },
    {
        "id": "10.7",
        "stage": "Stage 10.7",
        "title": "Security/compliance final hardening",
        "status": "planned",
        "depends_on": "Stage 10.6",
        "risk": "Residual governance gaps",
        "definition_of_done": "Security and compliance controls are fully verified",
        "kpi": "Control verification pass rate",
        "ships_in": "10.7.0",
        "features": ["Final security hardening", "Compliance verification"],
    },
    {
        "id": "10.8",
        "stage": "Stage 10.8",
        "title": "Performance and cost convergence",
        "status": "planned",
        "depends_on": "Stage 10.7",
        "risk": "Suboptimal cost/performance balance",
        "definition_of_done": "Performance and cost targets converge",
        "kpi": "Cost-performance index",
        "ships_in": "10.8.0",
        "features": ["Performance optimization", "Cost convergence controls"],
    },
    {
        "id": "10.9",
        "stage": "Stage 10.9",
        "title": "Contract freeze and final release governance",
        "status": "planned",
        "depends_on": "Stages 10.1-10.8",
        "risk": "Late governance/compatibility risks",
        "definition_of_done": "Final 10.0 governance baseline is signed off",
        "kpi": "Final release readiness score",
        "ships_in": "10.9.0",
        "features": ["Contract freeze", "Release governance baseline"],
    },
]
