# Generated by Django 4.2.7 on 2026-01-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('suite_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('test_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_suites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Suite',
                'verbose_name_plural': 'Test Suites',
                'db_table': 'test_suites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('passed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to=settings.AUTH_USER_MODEL)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='test_runner.testsuite')),
            ],
            options={
                'verbose_name': 'Test Run',
                'verbose_name_plural': 'Test Runs',
                'db_table': 'test_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testsuite',
            index=models.Index(fields=['suite_id'], name='test_suites_suite_i_8ccf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='testsuite',
            index=models.Index(fields=['status'], name='test_suites_status_29454e_idx'),
        ),
        migrations.AddIndex(
            model_name='testsuite',
            index=models.Index(fields=['created_by', '-created_at'], name='test_suites_created_8711c2_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['run_id'], name='test_runs_run_id_03f9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['suite', '-created_at'], name='test_runs_suite_i_97eef3_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['status'], name='test_runs_status_d63d51_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['-created_at'], name='test_runs_created_6e95dd_idx'),
        ),
    ]
