# Generated by Django 4.2.7 on 2026-01-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('documentation_sync', 'Documentation Sync'), ('s3_sync', 'S3 Sync'), ('codebase_analysis', 'Codebase Analysis'), ('ai_learning', 'AI Learning'), ('knowledge_extraction', 'Knowledge Extraction'), ('data_migration', 'Data Migration'), ('system_backup', 'System Backup')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operation Log',
                'verbose_name_plural': 'Operation Logs',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation_id'], name='operation_l_operati_fd1edf_idx'), models.Index(fields=['operation_type'], name='operation_l_operati_01172f_idx'), models.Index(fields=['status'], name='operation_l_status_208464_idx'), models.Index(fields=['started_by', '-created_at'], name='operation_l_started_0a435a_idx'), models.Index(fields=['-created_at'], name='operation_l_created_61eacf_idx')],
            },
        ),
    ]
