# Generated by Django 4.2.16 on 2026-04-09 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("page_type", models.CharField(blank=True, default="", max_length=100)),
                ("codebase", models.CharField(blank=True, default="", max_length=100)),
                ("surface", models.CharField(blank=True, default="", max_length=200)),
                ("flow_id", models.CharField(blank=True, default="", max_length=200)),
                ("era_tags", models.JSONField(blank=True, default=list)),
                ("route", models.CharField(blank=True, default="", max_length=500)),
                ("status", models.CharField(blank=True, default="", max_length=50)),
                ("auth_required", models.BooleanField(default=False)),
                ("purpose", models.TextField(blank=True, default="")),
                ("section_count", models.PositiveIntegerField(default=0)),
                ("component_count", models.PositiveIntegerField(default=0)),
                ("endpoint_count", models.PositiveIntegerField(default=0)),
                ("s3_bucket_id", models.CharField(max_length=300)),
                (
                    "s3_file_key",
                    models.CharField(
                        help_text="Relative key, e.g. json/<uuid>.json", max_length=500
                    ),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "sections_override",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Edited sections; merged over S3 spec in editor",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.CharField(blank=True, default="", max_length=254),
                ),
            ],
            options={
                "verbose_name": "Page spec",
                "verbose_name_plural": "Page specs",
                "ordering": ["-updated_at", "title"],
            },
        ),
    ]
