# Generated by Django 4.2.7 on 2026-01-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('component_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(db_index=True, max_length=255)),
                ('component_type', models.CharField(choices=[('text', 'Text Block'), ('image', 'Image'), ('code', 'Code Block'), ('table', 'Table'), ('heading', 'Heading'), ('list', 'List'), ('link', 'Link'), ('divider', 'Divider')], max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_components', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Component',
                'verbose_name_plural': 'Page Components',
                'db_table': 'page_components',
                'ordering': ['page_id', 'order'],
                'indexes': [models.Index(fields=['component_id'], name='page_compon_compone_7115da_idx'), models.Index(fields=['page_id', 'order'], name='page_compon_page_id_e76974_idx'), models.Index(fields=['component_type'], name='page_compon_compone_65d0fa_idx')],
            },
        ),
    ]
