from __future__ import annotations

import shutil
from pathlib import Path

from .paths import DOCS_ROOT
from .scanner import ERA_FOLDERS

IGNORED_DIRS = {
    "__pycache__",
    "scripts",
    ".git",
    "venv",
    "ideas",
    "backend/postman",
    ".pytest_cache",
    # Generated by `python cli.py validate-all --write-latest`
    "result",
    "errors",
}
IGNORED_FILES = {
    "README.md",
    "main.py",
    "cli.py",
}


def get_all_files() -> list[Path]:
    """Get all non-ignored files in the docs directory."""
    all_files = []
    for path in DOCS_ROOT.rglob("*"):
        if not path.is_file():
            continue
        # Check if it's in an ignored directory
        rel_path_posix = path.relative_to(DOCS_ROOT).as_posix()
        in_ignored_dir = any(
            rel_path_posix == ignored or rel_path_posix.startswith(ignored + "/")
            for ignored in IGNORED_DIRS
        )
        if in_ignored_dir:
            continue
        if path.name in IGNORED_FILES:
            continue
        all_files.append(path)
    return all_files


def get_all_markdown_contents() -> list[str]:
    """Get contents of all markdown files to search for references."""
    contents = []
    for path in DOCS_ROOT.rglob("*.md"):
        rel_path_posix = path.relative_to(DOCS_ROOT).as_posix()
        in_ignored_dir = any(
            rel_path_posix == ignored or rel_path_posix.startswith(ignored + "/")
            for ignored in IGNORED_DIRS
        )
        if in_ignored_dir:
            continue
        try:
            contents.append(path.read_text(encoding="utf-8"))
        except Exception:
            pass
    return contents


def find_unused_files() -> list[Path]:
    """Find all files that are not referenced in any markdown file."""
    all_files = get_all_files()
    contents = get_all_markdown_contents()
    
    unused_files = []
    for file_path in all_files:
        is_used = False
        filename = file_path.name
        
        # Heuristic: is the exact filename present in any of the markdown contents?
        for content in contents:
            if filename in content:
                is_used = True
                break
        
        if not is_used:
            unused_files.append(file_path)
            
    return sorted(unused_files)


def _is_under_era_folder(path: Path) -> bool:
    try:
        rel = path.resolve().relative_to(DOCS_ROOT.resolve())
    except ValueError:
        return False
    parts = rel.parts
    if not parts:
        return False
    top = parts[0]
    return top in ERA_FOLDERS


def find_unused_for_prune(*, exclude_era_folders: bool = True) -> list[Path]:
    """Unused candidates; optionally drop anything inside era directories."""
    found = find_unused_files()
    if not exclude_era_folders:
        return found
    return [p for p in found if not _is_under_era_folder(p)]


def quarantine_paths(paths: list[Path], quarantine_root: Path) -> tuple[list[Path], list[str]]:
    """
    Move files under quarantine_root preserving relative path under docs/.
    Returns (moved_paths, errors).
    """
    quarantine_root.mkdir(parents=True, exist_ok=True)
    moved: list[Path] = []
    errors: list[str] = []
    docs_resolved = DOCS_ROOT.resolve()
    for src in paths:
        try:
            rel = src.resolve().relative_to(docs_resolved)
        except ValueError:
            errors.append(f"skip (outside docs): {src}")
            continue
        dest = quarantine_root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        try:
            shutil.move(str(src), str(dest))
            moved.append(dest)
        except OSError as e:
            errors.append(f"{src}: {e}")
    return moved, errors
