# Generated by Django 4.2.16 on 2026-04-09 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JsonDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="URL-safe identifier, auto-generated from label",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Human-readable name", max_length=300),
                ),
                ("s3_bucket_id", models.CharField(max_length=300)),
                (
                    "s3_file_key",
                    models.CharField(
                        help_text="Relative key, e.g. json/<uuid>.json", max_length=500
                    ),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(default="application/json", max_length=100),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated tags",
                        max_length=500,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "uploaded_by",
                    models.CharField(blank=True, default="", max_length=254),
                ),
            ],
            options={
                "verbose_name": "JSON Document",
                "verbose_name_plural": "JSON Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
