# Generated by Django 4.2.7 on 2026-01-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONStore',
            fields=[
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('type', models.CharField(choices=[('postman_environment', 'Postman Environment'), ('config', 'Configuration'), ('data', 'Data'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='json_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JSON Store',
                'verbose_name_plural': 'JSON Stores',
                'db_table': 'json_store',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_id'], name='json_store_store_i_ed25f4_idx'), models.Index(fields=['key'], name='json_store_key_de86c7_idx'), models.Index(fields=['type'], name='json_store_type_1aec14_idx'), models.Index(fields=['created_by', '-created_at'], name='json_store_created_03fd40_idx')],
            },
        ),
    ]
